export const BUNDLED_PROMPTS: readonly string[] = [
  "What took longer than it should have today?",
  "Describe one small repair or fix you made around your home.",
  "How did the weather steer your plans today, if at all?",
  "List three objects you touched most often before noon.",
  "What conversation are you still carrying around right now?",
  "Where did you spend money this week, and why?",
  "Describe the last meal you cooked without looking anything up.",
  "What route do you walk, drive, or ride most often?",
  "Which task did you postpone until tomorrow, again?",
  "What sound did you hear first this morning?",
  "Write about a door you opened more than ten times today.",
  "What is one thing you know now that you didn't at breakfast?",
  "Describe your desk, table, or workspace exactly as it sits.",
  "Who did you help today, even in the smallest way?",
  "What appointment, deadline, or errand is closest on your calendar?",
  "Name the oldest object you used today, and its story.",
  "What did you carry in your pockets or bag today?",
  "Describe one email or message you rewrote before sending.",
  "What time did you wake up, and what woke you?",
  "Which room of your home saw the most activity today?",
  "Write the recipe of your day so far, step by step.",
  "What did you fix, patch, or tape together recently?",
  "What did you buy twice because the first one wore out?",
  "What queue did you stand in this week, and was it worth it?",
  "Name a skill you practiced without anyone noticing.",
  "What did you lend, borrow, or return lately?",
  "Describe the view from your window at midday.",
  "Which chore do you do without complaint, and why that one?",
  "What tool do you own that nobody else you know owns?",
  "Write about the last time you were early instead of late.",
  "What did you throw away today that took effort to make?",
  "Which subscription, bill, or renewal crossed your desk this month?",
  "Describe how you prepare your favorite drink, exactly.",
  "What did you say yes to, and what did it cost?",
  "Name the last photograph you took and what it shows.",
  "What errand takes you farther from home than any other?",
  "Which book, article, or manual is half-finished near you?",
  "Write down tonight's plan as if instructing a substitute.",
  "What did you measure, weigh, or count this week?",
  "Describe one habit you keep purely because it saves time.",
];
